### ISSUE TITLE
implement audit 

### ISSUE THREAD

**Issue by philipkcl** [culturesofknowledge/emlo-project#118]

**Comment by philipkcl** [comment]
@mirandalewis, 
We are start prepare to implement audit features.
In QA server, audit page seem not working after query.

![image](https://user-images.githubusercontent.com/97410502/204834270-83606c87-8681-4fb8-8c40-5c5ef80236a7.png)

* Do you have any idea about it? did I use the audit in wrong way ?
* if we can't fix this issues in QA server, do you mind screen capture some audit page features for us to implementation references?

**Comment by mirandalewis** [comment]
Dear Philip,

I’m afraid I don’t know why the audit page isn’t working for you on the QA server. It does take a long, long time to bring up a result. You might want to try searching on just one letter or person or place (using the ID number).

I’m copying in John to this reply in case he’s able to help with anything while I’m in The Hague.

Est,
Miranda

**Comment by philipkcl** [comment]
hi John  @jpnp, 

I studying original audit feature and I have some questions about audit.

In audit search page, is it only searching for records of `cofk_union_audit_literal`, correct?

what is usage of `cofk_union_audit_relationship` table?  which page are using `cofk_union_audit_relationship` table?

**Comment by jpnp** [comment]
Hi,
As I understand it when a relationship is changed/added, two audit entries are created.
The one in `cofk_union_audit_literal` is used in the search/display.  e.g.:

```
     audit_id |      change_timestamp      | change_user | change_type |        table_name     
   | key_value_text | key_value_integer |                                                  
                                                            key_decode                     
                                                                                         | 
         column_name           | new_column_value | old_column_value 
----------+----------------------------+-------------+-------------+-----------------------
---+----------------+-------------------+--------------------------------------------------
-------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------+-
-------------------------------+------------------+------------------
 11496401 | 2022-12-05 18:18:55.546843 | cofkmiranda | New         | cofk_union_manifestati
on | W1028537-b     |           2268376 | xxxCofkLinkStartxxxxxxCofkHrefStartxxxhttps://eml
o-edit.bodleian.ox.ac.uk/interface/union.php?iwork_id=1028537xxxCofkHrefEndxxxRydboholmssam
lingen, De la Gardieska handlingar: Pontus Fredrik De la Gardie, E 7651xxxCofkLinkEndxxx | 
Relationship: Is in repository | Riksarkivet      | 
```
However, a relationship has two sides (termed left and right in EMLO), and this entry only records one side of the relationship (manifestation W1028537-b in this case) as there is not space for both in `cofk_union_audit_literal`.

So an entry is also created in `cofk_union_audit_relationship` when a relationship is changed.  This can record both sides of the relationship (i.e. that this in_repository relationship references cofk_union_institution  88).  This fact is not recorded in `cofk_union_audit_literal`, but may be required if old edits needed to be reversed or changed.

```
     audit_id |      change_timestamp      | change_user | change_type |     left_table_name   
   | left_id_value_new |                                                                   
                                       left_id_decode_new                                  
                                                                        | left_id_value_old
 | left_id_decode_old | relationship_type | relationship_decode_left_to_right | relationshi
p_decode_right_to_left |    right_table_name    | right_id_value_new | right_id_decode_new 
| right_id_value_old | right_id_decode_old 
----------+----------------------------+-------------+-------------+-----------------------
---+-------------------+-------------------------------------------------------------------
-------------------------------------------------------------------------------------------
------------------------------------------------------------------------+------------------
-+--------------------+-------------------+-----------------------------------+------------
-----------------------+------------------------+--------------------+---------------------
+--------------------+---------------------
 11496400 | 2022-12-05 18:18:55.546843 | cofkmiranda | New         | cofk_union_manifestati
on | W1028537-b        | xxxCofkLinkStartxxxxxxCofkHrefStartxxxhttps://emlo-edit.bodleian.o
x.ac.uk/interface/union.php?iwork_id=1028537xxxCofkHrefEndxxxRydboholmssamlingen, De la Gar
dieska handlingar: Pontus Fredrik De la Gardie, E 7651xxxCofkLinkEndxxx |                  
 |                    | stored_in         | Is in repository                  | Has content
s                      | cofk_union_institution | 88                 | Riksarkivet         
|                    | 
```
I don't know if the table is used in the interface at all.  I think its primary reason is to record the audit info so that the full detail of changes could be recovered by a script if they were needed.

**Comment by philipkcl** [comment]
@jpnp, that good to know, Thanks for the information.
