### ISSUE TITLE
Setup code repository for EMLO

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#14]
We were thinking of using the repository called [emlo](https://github.com/culturesofknowledge/emlo) which already exists in the [Cultures of Knowledge](https://github.com/culturesofknowledge) Github organisation. It is an empty repository with 5 old issues and hasn't been touched in 7 years.

**Comment by jpnp** [comment]
This is an upgrade to emlo-edit so could be emlo-edit-new, or perhaps use a branch on emlo-edit?
