### ISSUE TITLE
Prepare deployment procedure for production and QA server

### ISSUE THREAD

**Issue by philipkcl** [culturesofknowledge/emlo-project#143]
since many components using the same DB schema. we need to be careful to avoid impact on other components when database migration.

add to email loop: @anusharanganathan @J4bbi

**Comment by philipkcl** [comment]
@jpnp, we are preparing  deployment procedure, we have some questions before prepare procedure.

* Django have their method (`migration system`) to handle database migration which required those table created by Django. So, I would like to confirm:
  * is it okay to re-create table by Django in production environment (data will be keep/copy in new table) ?
  * is it any concern for other components if re-create table?

**Comment by jpnp** [comment]
Just to understand.  This is new tables made by Django rather than the existing ones?

I don't expect any problem.  Obviously, we'll test on QA before trying on the production environment.

**Comment by philipkcl** [comment]
created docker setting and merged to `main` branch .

https://github.com/culturesofknowledge/site-edit-2/blob/main/docs/deployment_procedure.md
