### ISSUE TITLE
About delete Authors and Senders 

### ISSUE THREAD

**Issue by philipkcl** [culturesofknowledge/emlo-project#166]
If I go into a single letter, I might need to change the Author or Recipient, i.e. delete the current author or the recipient and replace him/her with a new author or recipient, because the attribution of the authorship has changed. How do I do this?
e.g. in Work ID 969014: I can see where the recipient is, but I have no way to delete the current one. 
I can’t see where the author is listed, although there is a new way to add an additional author.
This is EMLO-Edit OLD:
![image](https://user-images.githubusercontent.com/97410502/216966654-a564a876-f085-4196-958d-13e4b4aabe76.png)

And this is EMLO-Edit NEW:

![image](https://user-images.githubusercontent.com/97410502/216966704-38bbc32e-f5b2-4c11-9eb1-d0e50f2d1e50.png)

**Comment by philipkcl** [comment]
@mirandalewis,  about missing checkbox `Delete from 'author/sender' list` or `Delete from 'addressee' list` in work form. 

In order to delete author in record of work. we can uncheck all checkbox and than press `save` button.
![image](https://user-images.githubusercontent.com/97410502/216967740-2474d79b-e8d6-49b0-bd33-03832e352fd2.png)

**Comment by mirandalewis** [comment]
Dear Philip,

Ah yes, thank you. I see. This works well. I just have to think of a way we can make this self-explanatory. Thank you very much. It works!

All very best,
Miranda
