### ISSUE TITLE
sender or recipient doesn’t show through but rather the underlying code

### ISSUE THREAD

**Issue by philipkcl** [culturesofknowledge/emlo-project#167]
Also, in EMLO-Edit-NEW when I add a new sender or recipient to a work and then review it, the name doesn’t show through but rather the underlying code:

So, the newly added author isn’t showing through at all, and there is no way to correct the author by changing people. 
And there is no way to change the recipient/addressee.

**Comment by J4bbi** [comment]
I believe I've fixed this here:

https://github.com/culturesofknowledge/site-edit-2/commit/713ebe27520d0c1c9a1f2ce829e1a5a09998fff6
