### ISSUE TITLE
Concurrently updated tabs

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#176]
It’s great that new tabs open when you go into to edit. However, they multiply rather quickly. In EMLO-Edit-OLD, when you make a change in the new tab, and click save, it refreshes and closes back, refreshing the list in the original list you were working in. It’s amazingly useful. Will this be possible?

**Comment by J4bbi** [comment]
@anusharanganathan and @philipkcl , I'm not sure how this would easily be implementable, either some weird JS or possibly refreshing tabs, I suggest this be put on hold

**Comment by anusharanganathan** [comment]
I agree with you @j4bbi -  This just doesn't sound easy or like the right thing to do. Let's bring this up with Neil and John

**Comment by anusharanganathan** [comment]
Thinking out loud, the way to do it would be 
* from results - select edit on a record (the search parameters are passed to edit)
    * The edit page opens in the same tab
    * In addition to all of the current options in edit, if the redirect parameter is present,  a button to `save and go back to search results` will be available
   * clicking on `save and go back to search results` will redirect to search results page **(oh she also wanted to have the scroll bar in the same place - perhaps there's a js trick for that)**
   * clicking on 'save` and you stay on the page

Is this doable? Shall we present this as an option?

**Comment by philipkcl** [comment]
@anusharanganathan ,  did you present the option , any feedback from Client?

If no, I will try to implement that

**Comment by anusharanganathan** [comment]
No I didn't @philipkcl. Just go ahead and implement this solution
