### ISSUE TITLE
Display as ‘down the page’

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#178]
We’ve lost the option to display as ‘down the page’, which is more like ‘print view’ (rather than across the page, in spreadsheet format). I’m guessing it’s a casualty of the new style. It’s not the end of the world as we don’t use it that often, but it may have repercussions for the display of the collect review pages as it’s similar to those? I’m just pointing it out.

**Comment by anusharanganathan** [comment]
We will not be developing this view, as there is no use case for it. We can come back to this if needed
