### ISSUE TITLE
Add Authorization rule for upload

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#18]
EMLO Edit supports a simple role based authorization system. Each user is assigned to one or more roles, which gives them access to perform tasks. 

To start with, the system supports the following roles

## Reader 
* A Reader is able to search and view records within EMLO Edit
* A reader cannot add / edit / delete any information. 
* The user cannot view / search audit records

## Editor 
Has all of the privileges of a reader and in addition can do the following
* Create, edit or delete a work and the entities associated with a work
    * The editor can add an editorial notes intended for public display associated with a work or an entity, but 
    * cannot Edit or delete editorial notes intended for public display associated with a work or an entity.
* Can add both public-facing notes as well as back-end display only working notes when creating a work or other entities
* Can upload a spreadsheet containing works and the associated entities
* Can review uploads, accept or reject individual works, a series of works or all works from an uploaded set. 
* An editor cannot add / edit / delete users and manage user roles
* An editor cannot trigger a data export to the front end

## Supervisor
A supervisor has all of the privileges of an editor and in addition, can do the following
* Edit or delete editorial notes intended for public display associated with a work or an entity.
* Set a refresh of data from EMLO-Edit to the front end.
    * This is to manually trigger an export of the data for use by the front end. When triggered manually, the job will run overnight.  There is also a scheduled job that does this weekly.
* Manage users and their roles
* Create new users and assign them to one or more roles
* Edit user details and modify a user’s role
* Delete users

An initial administrator user is created by the system. Following that, users are primarily created using the user interface. 

It should be possible to add new roles and modify the scope of the role in the future. For example, when incorporating EMLO Web Form, the role editor will likely be split into contributor and editor roles. The contributor role would permit a user to create a work, edit their work, delete their work, and submit their work for review. The editor role will be able to not only contribute, but also review submissions.

**Comment by anusharanganathan** [comment]
This will be implemented as a part of https://github.com/culturesofknowledge/emlo-project/issues/220

**Comment by philipkcl** [comment]
missed
* An editor cannot trigger a data export to the front end

double check all requirement have been implemented
