### ISSUE TITLE
Person search: The last edited by column displays the wrong date

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#188]
The `last edited by` column displays the wrong date

It looks like the first edit date. Certainly not last

The search I think matches with what is displayed in the column i.e not searching on last edit date. 

I have been editing http://emlo-edit.cottagelabs.com/person/form/926571

* my edits exist
* It did not show up in the search results when I searched for it by last edit date. 
* The last edited by should have been `01 Mar 2023, hh:mm, admina`, but is instead `Dec. 19, 2019, 11:40 a.m. by cofkbot`

**Comment by J4bbi** [comment]
fixed in https://github.com/culturesofknowledge/site-edit-2/pull/76
