### ISSUE TITLE
Person search: Other details 

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#189]
According to the blurb on the form label for Other details in person search, this should search
`Summary of any other information about the person or group, including membership of organisations, known geographical locations, researchers' notes and related resources.`
    
* It is not searching locations. 
    I added Abingdon in birth place in http://emlo-edit.cottagelabs.com/person/form/926571 and could not search on it

**Comment by J4bbi** [comment]
The way the other details are generated is primarily from abbreviations, synonyms and titles or roles.

There is a relation mappable between a person and a location, this is stored in the table `cofk_person_location_map`.

`select * from cofk_person_location_map where relationship_type = 'was_born_in_location';`
gives a total of 169 results, indicating that it's not very highly used (see [data-1683123068999.csv](https://github.com/culturesofknowledge/emlo-project/files/11383355/data-1683123068999.csv))

Take for instance, location_id = 59, Utrecht.

There is a mapping between Utretch and `cofk_union_person-iperson_id:000901275`, Vanlore, Peter (Sir).

His Names and titles/roles field reads: 

> Vanlore, Peter (Sir) ~ Synonyms: Sir Peter Vanlore the Elder; Pieter van Loor ~ Titles/roles: first baronet; merchant, jeweller, and moneylender; paternal grandfather of Jacoba (Vanlore) Zinzan/Alexander

with no indication of Utrecht as a result he does not show up in the results if you search for "Utrecht"


Using another example, Abingdon (location_id = 653). There is not a single result in `cofk_person_location_map` for that location.

However if you search for people using "Abingdon" you get 11 results, including 

> Dayrell, Walter~ Titles/roles: of Abingdon, Oxfordshire

This seems to be an incorrectly generated title, where the title itself is missing but the location isn't.

**Conclusion**
There does not seem to be a functioning feature in EMLO Edit old that makes associated locations searchable via the Names and titles/roles field in people search.
