### ISSUE TITLE
Languages can not be searched/saved

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#208]
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/c27a4206-9e42-44b4-9e1a-3d0e1cf8a874)

Go to Main menu and select Select languages for use in project

**Comment by philipkcl** [comment]
do you mean language in work form can't be save?

**Comment by J4bbi** [comment]
no this is for the favorite language feature, I'm implementing it
