### ISSUE TITLE
Prepare UI design templates for dev

### ISSUE THREAD

**Issue by sssoz** [culturesofknowledge/emlo-project#24]
@anusharanganathan Hope it’s OK — creating this GH issue to track my templating / designing work on the kanban as well. Feel free to move it or delete if it’s not appropriate. 

Ensure that the following are ready for handoff to developers: 

- [x] the search interface with tabular results
- [x] where you expect the forms to add new works to be displayed (how does a user get there)
- [x] where you expect the forms to edit work to be displayed
- [x] integrate modals and tooltips (e.g. for help text) — Tippy.js?
- [ ] toggle between layout styles
- [ ] finish "TODO:" comments 
- [ ] integrate slide-out menu for search form
- [ ] integrate dropdown menu items (e.g. for header nav)
- [ ] Also, template files for integration with Django would be useful as we are starting to add forms (use Jinja)
- [ ] Update prototype templates following feedback in https://docs.google.com/document/d/19d4JOVOn4ojTXVbjsIhMYOZXtC2UE0UCqids83eS-ZI/edit?usp=sharing

**Comment by sssoz** [comment]
@anusharanganathan From the Django documentation for their templating engine: https://docs.djangoproject.com/en/4.0/topics/templates/

> A Django project can be configured with one or several template engines (or even zero if you don’t use templates). **Django ships built-in backends for its own template system, creatively called the Django template language (DTL), and for the popular alternative [Jinja2](https://jinja.palletsprojects.com/).** Backends for other template languages may be available from third-parties. You can also write your own custom backend, see [Custom template backend](https://docs.djangoproject.com/en/4.0/howto/custom-template-backend/)

In order to keep things simple, I will use Jinja2 templating (as it is more common than Django’s own templating language). Currently, my prototype uses Nunjucks which is similar to Jinja — it’ll be easier for me to convert the templates.

**Comment by anusharanganathan** [comment]
Thank you @sssoz. We also don't mind DTL. We use that in another project.

**Comment by sssoz** [comment]
@anusharanganathan I meant that I believe it would be more difficult to convert the Nunjuck templates into DTL! Hope that's OK
