### ISSUE TITLE
Is timestamp inaccurate?

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#265]
The time stamp is not working correctly. It should be 15.26 and not 15:36 a.m.

**Comment by philipkcl** [comment]
more details? where did you find 15.26 and 15:36 am ?

**Comment by J4bbi** [comment]
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/d16a4498-add4-424d-95c4-e77b16078389)

Miranda just says it's not working, on page 4
