### ISSUE TITLE
People: Synonyms: In the person record, these need to display in a list, not in a continuous line

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#275]
Please, otherwise it’s a) hard to see what’s there, or b) set them easily into alphabetical order (which I’m doing increasingly) with an easy sort / copy / paste using excel.
EMLO-Edit-NEW: 
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/4880a9e7-5ca1-4cac-9f78-0422f2c18275)
And EMLO-Edit-OLD:
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/70105238-8258-4ec2-adcc-1fe838e33a2f)

**Comment by philipkcl** [comment]
@mirandalewis,

Look like this problems also happen in `Futher detials of roles / titles`:
![image](https://github.com/culturesofknowledge/emlo-project/assets/97410502/67c30202-fe5e-4085-b1cb-721da15fa1f9)

I will also fix it in `Futher detials of roles / titles`

Please let's me know if any other field have similar issues.
