### ISSUE TITLE
People search resources not displayed correctly

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#277]
When I search on a person to check the person record to see what information we have for them, the synonyms and roles are working well (better than EMLO-Edit-OLD, although they’re taking up a lot of space, which is hard when you have a long, long list to skim through/compare)

However, it’s 
a) hard to distinguish at a glance what we have, e.g. In EMLO-Edit-OLD, I can see very clearly the different related resources, e.g.:
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/dd16b5f2-56b7-4628-88ab-bda8bb6f1998)
Compared to EMLO-Edit-New:
![image](https://github.com/culturesofknowledge/emlo-project/assets/5488106/d5b2f3e9-6697-4114-856c-b89bb41125e5)
b) I’m not able to click on the Descriptors or the links to open the resource from that place (which I often need to do).
c) and I am not able to copy for pasting any of the data easily.
I suggest that we don’t display the urls, but rather stick with what was in EMLO-Edit-Old, and have clickable descriptors. You have done this in locations and repositories, etc. and it works well there.

**Comment by philipkcl** [comment]
`related resources` in `Other details` should be updated in latest version
