### ISSUE TITLE
Not all sort by fields work

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#280]
Removing CofkUnionQueryableWork and making searches of related entities means that some sort by values have stopped working.

Work:
- addressee
- Author/sender
- Day
- Destination (standardised)
- Flags
- Language of work
- Manifestations
- Origin (standardised)
- Related resources

People:
- other details

Location:
- related resources

**Comment by J4bbi** [comment]
@philipkcl , I can not think of a way to sort by the related fields

I thought of annotating when passing to the update_query

https://github.com/culturesofknowledge/site-edit-2/blob/892a97317bdc7e32450f8e2b113c4a0c23581236/work/views.py#L1242

but I could not come up with a way to sort only on those related cofkworkpersonmap persons that had a relationshiptype "created"

can you think of an way to order by these fields?

**Comment by philipkcl** [comment]
did this problems can be find in feedback doc? if yes, what is original description look like ?

some fields can be filter and sorting by`annotate` 

but some fields have no meaning to be sort e.g. `related resources`, `other details` should be remove from sort options or discuss with Client

**Comment by J4bbi** [comment]
No, this wasn't in the feedback doc.

Just something I observed.

Yes, I suspected `annotate` could do it but it needs to be a conditional annotation and I couldn't manage to come up with one that works.

I suppose sorting by related `resources` or `other details` has little to no utility, good point
