### ISSUE TITLE
Cannot search without refresh when going back from search results to work search form

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#286]
In work search
* Select `Advanced search`
* In field for abstract
  *  Select `not contain`
  * Type `Dryden`
* Click on search
  > I get 500 error page as mentioned in issue https://github.com/culturesofknowledge/emlo-project/issues/285
* Click on browser back button

The form search button now says `Loading ….`. It does not go away until I refresh the page

<img width="357" alt="Screenshot 2024-12-05 at 13 10 55" src="https://github.com/user-attachments/assets/a6fa80ad-25e0-471e-9aa2-ba8da3fe4d24">

**Comment by philipkcl** [comment]
that could be only happen when `does not contain` create 500 error.

Please let's me know if this loading... issues still exist after `does not contain` error fixed
