### ISSUE TITLE
Add database authentication

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#3]
Authentication using database in the UI.

Hrafn to give link to tutorial on how to do this in Django.

**Comment by J4bbi** [comment]
Hey @philipkcl 

Here is documentation on [user authentication](https://docs.djangoproject.com/en/4.0/topics/auth/)

I do recommend [the introductory tutorial](https://docs.djangoproject.com/en/4.0/intro/tutorial01/), it's very good and comprehensive.

Also it is a good idea to look at [the deployment checklist](https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/). @anusharanganathan  I think it's also relevant to you.

**Comment by philipkcl** [comment]
@anusharanganathan , 
what is target of this tasks? the django have very good auth feature ([login, permission, groups](https://docs.djangoproject.com/en/4.0/topics/auth/default/)) ready for use. Do I need to create login page for this tasks ?

@J4bbi , should we use `class CofkUser(AbstractBaseUser, PermissionsMixin)`  as user model, right?

**Comment by J4bbi** [comment]
@philipkcl, yes correct 

good job, you are quick to learn

**Comment by philipkcl** [comment]
just learn from `pstf`, `pstf` have good and clean code , easy to understand.
