### ISSUE TITLE
Forms, general improvement

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#48]
- It would be good to improve the signage in EMLO-Edit-New so it’s clear we’re working in an add new person form rather than in an edit person form, e.g. in EMLO-Edit-Old
- Please can the submit/save box be in another colour so we can distinguish it easily.

**Comment by philipkcl** [comment]
>Please can the submit/save box be in another colour so we can distinguish it easily
@J4bbi does that solved by `actionbox` ?

**Comment by J4bbi** [comment]
> > Please can the submit/save box be in another colour so we can distinguish it easily
> > @J4bbi does that solved by `actionbox` ?


@philipkcl 
I've included a fix for that in this branch https://github.com/culturesofknowledge/site-edit-2/tree/fix/search_improvements
