### ISSUE TITLE
Create API to for spreadsheet upload

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#5]
- [ ] API endpoint to upload spreadsheet
- [ ] API endpoint to validate spreadsheet
- [ ] API endpoint to ingest spreadsheet

**Comment by philipkcl** [comment]
@anusharanganathan more details about requirements of those API?

**Comment by anusharanganathan** [comment]
## API for upload

### /upload

PUT file - 200, or error
Start validation in background
Response:
​	return file id
​	Message from validation

### /upload/file_id

GET - get status of validation

Response:
​	return file id
​	Message from validation

**Comment by philipkcl** [comment]
as discussed, no need to implement API any more
