### ISSUE TITLE
Edit between tabs

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#52]
In EMLO-Edit-Old, when we edit a record, it opens in a new (browser) tab. We make the change, we save, we ask it to refresh and it goes to the original search results and updates then so we can check the change. We have got used to the review stage of the changes made, and it is useful.

**Comment by J4bbi** [comment]
@philipkcl , was this done?

**Comment by philipkcl** [comment]
all non closed issues is incomplete except it is duplicate issues

**Comment by philipkcl** [comment]
duplicated issues
* https://github.com/culturesofknowledge/emlo-project/issues/176
