### ISSUE TITLE
Person form issue

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#53]
The Add organization button is not working properly. In EMLO-Edit-Old, there is the ability to add an organization /group by ticking the relevant box, which then opens up the ‘type of organization’, and the foundation/end of operation boxes for dates, etc.
The add relationships section, etc. is not working.

**Comment by philipkcl** [comment]
![image](https://user-images.githubusercontent.com/97410502/201941272-97e5b21d-c190-4ded-a5dd-bf68e6169807.png)

@mirandalewis, I not sure how to show in EMLO-Edit-Old, do you know about it?

**Comment by philipkcl** [comment]
Thanks @mirandalewis, I will make some changes for organisation. 
The update will be provide in next Friday (18 Nov).
let's review it together in onsite meeting.
