### ISSUE TITLE
Place form

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#54]
Alternative names for place isn’t working. We need to be able to add synonyms on separate lines and to have the box able to expand accordingly.

**Comment by philipkcl** [comment]
@J4bbi  I not sure which field not working 

![image](https://user-images.githubusercontent.com/97410502/204506922-1187dcc0-12d7-4c18-8a2a-e67fd028db56.png)

**Comment by J4bbi** [comment]
@philipkcl , sorry for not responding earlier, it must be the "Alternative names for location"

**Comment by philipkcl** [comment]
@J4bbi tested, it work fine. Please provide more detail about problem of this fields.

![image](https://user-images.githubusercontent.com/97410502/213460018-983be63d-1050-47f7-af28-b2c24674d599.png)

**Comment by J4bbi** [comment]
Alt names for location needs to be a textarea in which each location is in a newline.
