### ISSUE TITLE
Work form issue

### ISSUE THREAD

**Issue by J4bbi** [culturesofknowledge/emlo-project#55]
When they add the abstract in the other box, they will sometimes copy how it appears in the card catalogue, with the line spaces to make it look exactly how it appeared in the letter. We need to preserve that and display as such in the UI (it does in old EMLO Edit) -- gathered from our meeting

**Comment by anusharanganathan** [comment]
They want breaks and paragraphs preserved

**Comment by J4bbi** [comment]
Tested in Abstract field for works. Is working as expected
