### ISSUE TITLE
Setup test infrastructure

### ISSUE THREAD

**Issue by anusharanganathan** [culturesofknowledge/emlo-project#9]
* Use the existing QA infrastructure to deploy development.
* It will be a parallel docker instance running the containers for the new development. 
* Import the data from the latest production database dump into the database (union and collect databases) (depends on issue #8)
* Setup firewall, DNS and Nginx to serve the docker containers to the new end point (depends on issue #11)

**Comment by philipkcl** [comment]
it should mean http://emlo-edit.cottagelabs.com
